---
name: Sudoku-Typescript CD workflow

on:
  # push:
  #   branches:
  #     - main
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          yarn install

      - name: Test
        run: |
          yarn test --watchAll=false
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test
  #   steps:
  # deploy:
  #   name: Deploy to firebase
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
